public virtual class DmlUtil {

	public virtual void insertData(List<SObject> data) {
		insert data;
	}
	public virtual void insertData(SObject data) {
		insert data;
	}

	public virtual void updateData(List<SObject> data) {
		update data;
	}
	public virtual void updateData(SObject data) {
		update data;
	}

	public virtual void deleteData(List<SObject> data) {
		delete data;
	}
	public virtual void deleteData(SObject data) {
		delete data;
	}
}