@IsTest
private class TestDeploymentClassTest {
    @IsTest
    static void testTestDeploymentClass() {
        TestDeploymentClass cls = new TestDeploymentClass();
        System.debug(LoggingLevel.DEBUG, 'TEST');
        System.debug(LoggingLevel.DEBUG, 'TEST');
        System.debug(LoggingLevel.DEBUG, 'TEST');
        System.debug(LoggingLevel.DEBUG, 'TEST');
        System.debug(LoggingLevel.DEBUG, 'TEST');
        System.debug(LoggingLevel.DEBUG, 'TEST');
    }
}
